name: presubmit GitHub Actions workflow validator
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  presubmit-github-actions-workflow-validator:
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-presubmit-github-actions-workflow-validator.yml@main
