name: reusable go container apps
on:
  workflow_call:
    inputs:
      updateGoVersionAutoMerge:
        type: boolean
        default: false
        required: false
        description: |
          specifies whether to auto merge PRs for Go version updates to go.mod files
      containerScanningEnabled:
        type: boolean
        default: false
        required: false
        description: |
          specifies whether to enable container scanning for each image built
      containerBuildEnabled:
        type: boolean
        default: ${{ github.ref == 'refs/heads/main' || contains(fromJSON('["workflow_call", "release"]'), github.event_name) }}
        required: false
        description: |
          specifies whether to enable container builds. Defaults to on the main branch, workflow_call or release
      push:
        required: false
        type: boolean
        default: ${{ github.ref == 'refs/heads/main' }}
        description: |
          set to true to push an image to a registry. When set to false, it will build and exit
    outputs:
      images:
        value: ${{ jobs.build.outputs.images }}
jobs:
  go-build:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-go-build-smoke-test.yml@main
    with:
      paths: ${{ inputs.paths }}
  build:
    if: ${{ contains(fromJSON('["workflow_call", "push", "release"]'), github.event_name) && inputs.containerBuildEnabled }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-ko-build.yml@main
    with:
      registryOverride: ${{ inputs.registryOverride }}
      paths: ${{ inputs.paths }}
      push: ${{ inputs.push }}
  gofmt:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-gofmt.yml@main
  golangci-lint:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-golangci-lint.yml@main
  go-test:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-go-test.yml@main
  go-vet:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-go-vet.yml@main
  govulncheck:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-govulncheck.yml@main
  goimports:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-goimports.yml@main
  update-go-version:
    if: ${{ contains(fromJSON('["workflow_call", "schedule"]'), github.event_name) }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-update-go-version.yml@main
    with:
      autoMerge: ${{ inputs.updateGoVersionAutoMerge }}
  release-please:
    if: ${{ contains(fromJSON('["workflow_call", "push"]'), github.event_name) && github.ref == 'refs/heads/main' }}
    uses: BobyMCbobs/todo-list-etcd/.github/workflows/reusable-release-please.yml@main
